### ISSUE TITLE
需要多少显存可以跑训练？

### ISSUE THREAD

**Issue by badarrrr** [THUDM/LongWriter#17]
### System Info / 系統信息

1

### Who can help? / 谁可以帮助到您？

1

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1

### Expected behavior / 期待表现

1

**Comment by bys0318** [comment]
你好，GLM-4-9B/Llama-3.1-8B模型32k长度训练需要～80G的显存

**Comment by mrpen2** [comment]
请问用vllm部署的话，大概需要多少显存

**Comment by bys0318** [comment]
vllm部署应该20GB左右显存就够

**Comment by badarrrr** [comment]
谢谢回复！
