### ISSUE TITLE
请问训练支持输入的最大长度是32k吗，若文件内容是1M，有什么处理建议吗？

### ISSUE THREAD

**Issue by thunder95** [THUDM/LongWriter#24]
如题。 谢谢大佬指导。

**Comment by bys0318** [comment]
我们的训练代码暂时只支持最大32k长度的训练，如果要在更长序列上训练需要换用megatron框架或者ring attention的技术。对于超过训练最大长度的序列长度，例如1M，除了截断，还可以用RAG或Summarization的方式先将序列长度降低到32k之内再输入模型。可参考[longbench论文](https://arxiv.org/abs/2308.14508)中测试时用到的context compression方法。

**Comment by thunder95** [comment]
好的 谢谢大佬解答。
