### ISSUE TITLE
适配glm4项目openai接口

### ISSUE THREAD

**Issue by JACKYLUO1991** [THUDM/LongWriter#29]
### System Info / 系統信息

适配glm4项目中的openai接口时，文本回复后会额外出现<|system>或者<|assistant>，请问如何解决呢？

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

启动openai server，修改stop_token_ids后会出现。

### Expected behavior / 期待表现

是否能够去掉额外的输出呢？

**Comment by bys0318** [comment]
可以在得到输出后post process一下，手动过滤掉<|system|><|assistant>这种特殊字符串。
