### ISSUE TITLE
Question about the weight calculation

### ISSUE THREAD

**Issue by XingLuxi** [THUDM/LongWriter#37]
https://github.com/THUDM/LongWriter/blob/4b78b665b13fc7fbd1093dcd15d9425501133941/train/main.py#L74

I noticed that in the DataCollatorForLMPackDataset, the pre-computed weight is divided by 30.

What is the meaning of the scalar 30 here?

**Comment by bys0318** [comment]
Hi, dividing by 30 in here is to prevent overflow in case the value is too large, it won't affect the result.

**Comment by XingLuxi** [comment]
Get the point! Thx!
